server:
  port: 8083
zk:
  url: 106.14.148.237:2181
  timeout: 3000
  namespace: workspace
  lockPath: /mylock

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

