server:
  port: 8082

spring:
  mvc:
    view:
      prefix: /WEB-INF/JSP/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.14.148.237:3306/xchat?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: bigdata
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    host: 192.168.1.183
    port: 6379
    password: sszn
    timeout: 0
    database: 1
  rabbitmq:
    addresses: 47.101.151.28:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10

## 打开mybatis的日志输出 ##
#logging:
#  level:
#    com.xx.xchat.dao.mybatis: DEBUG

## 在生产环境中为false，关闭swagger ##
swagger:
  enable: true

## ExecutorType.SIMPLE: 这个执行器类型不做特殊的事情。它为每个语句的执行创建一个新的预处理语句。
## ExecutorType.REUSE: 这个执行器类型会复用预处理语句。
## ExecutorType.BATCH: 这个执行器会批量执行所有更新语句,如果 SELECT 在它们中间执行还会标定它们是 必须的,来保证一个简单并易于理解的行为。
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.xx.xchat.entity.enums
  type-aliases-package: com.xx.xchat.entity
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true #下划线转驼峰开启
    default-executor-type: reuse
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志打印
  global-config:
    enable-sql-runner: true
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID", ID_WORKER_STR: "分布式全局唯一ID 字符串类型";
      id-type: id_worker_str
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

zk:
  url: 106.14.148.237:2181
  timeout: 3000
  namespace: workspace
  lockPath: /mylock

netty:
  port: 18001


